base_images:
  cli:
    name: "4.15"
    namespace: ocp
    tag: cli
  cli-ocm:
    name: cli-ocm
    namespace: ci
    tag: latest
  openshift-virtualization-tests:
    name: openshift-virtualization-tests
    namespace: ci
    tag: latest
  rosa-aws-cli:
    name: rosa-aws-cli
    namespace: ci
    tag: latest
  upi-installer:
    name: "4.15"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
images:
- build_args:
  - name: OCP_VERSION
    value: "4.15"
  - name: OC_CLI_VERSION
    value: latest
  context_dir: cnv-ci
  dockerfile_path: Dockerfile
  to: cnv-ci
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.15"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: cnv-interop-aws
  cron: 0 6 25 10 *
  steps:
    cluster_profile: aws-cspi-qe
    env:
      COMPUTE_NODE_REPLICAS: "1"
      COMPUTE_NODE_TYPE: c5n.metal
      FIREWATCH_CONFIG: |
        {
          "failure_rules":
            [
              {"step": "*deploy-portworx", "failure_type": "pod_failure", "classification": "Test Execution", "group": {"name": "lp-tests", "priority": 2}, "jira_additional_labels": ["!default","interop-tests"]},
              {"step": "*cnv-tests-e2e-deploy", "failure_type": "pod_failure", "classification": "Test Execution", "group": {"name": "lp-tests", "priority": 2}, "jira_additional_labels": ["!default","interop-tests"]},
              {"step": "*cnv-tests-e2e-deploy", "failure_type": "test_failure", "classification": "Test Failure", "jira_project": "CNV", "group": {"name": "lp-tests", "priority": 2},"jira_additional_labels": ["!default","interop-tests"],"jira_assignee":"ryasharz@redhat.com"},
              {"step": "*virtualization-tests", "failure_type": "test_failure", "classification": "Test Failure", "jira_project": "CNV", "group": {"name": "lp-tests", "priority": 2},"jira_additional_labels": ["!default","interop-tests"],"jira_assignee":"ryasharz@redhat.com"}
            ]
        }
      FIREWATCH_CONFIG_FILE_PATH: https://raw.githubusercontent.com/CSPI-QE/cspi-utils/main/firewatch-base-configs/aws-ipi/lp-interop.json
      FIREWATCH_DEFAULT_JIRA_ADDITIONAL_LABELS: '["4.15-lp", "rosa-classic-lp", "cnv-lp"]'
      FIREWATCH_DEFAULT_JIRA_PROJECT: LPINTEROP
      FIREWATCH_FAIL_WITH_TEST_FAILURES: "true"
      OCM_LOGIN_ENV: staging
      OCP_VERSION: "4.15"
      OPENSHIFT_VERSION: "4.15"
      REGION: us-west-2
    test:
    - ref: cucushift-installer-check-cluster-health
    - ref: interop-tests-deploy-portworx
    - ref: interop-tests-cnv-tests-e2e-deploy
    - ref: interop-tests-openshift-virtualization-tests
    workflow: firewatch-rosa-aws-sts
zz_generated_metadata:
  branch: cnv-4.15
  org: RedHatQE
  repo: interop-testing
  variant: cnv-portworx-ocp4.15-lp-rosa-classic
